openapi: 3.0.0
info:
  title: Sample API
  description: A simple sample API for testing
  version: 1.0.0
servers:
  - url: https://jsonplaceholder.typicode.com
paths:
  /posts:
    get:
      operationId: getPosts
      summary: Get all posts
      description: Retrieve all posts from the API
      parameters:
        - name: userId
          in: query
          description: Filter posts by user ID
          required: false
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
  /posts/{id}:
    get:
      operationId: getPost
      summary: Get a specific post
      description: Retrieve a specific post by ID
      parameters:
        - name: id
          in: path
          description: Post ID
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
        '404':
          description: Post not found
    post:
      operationId: createPost
      summary: Create a new post
      description: Create a new post
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                body:
                  type: string
                userId:
                  type: integer
      responses:
        '201':
          description: Post created successfully